.TH adv 1
.SH NAME
adv - mkdir a dir and cd into it

.SH SYNOPSYS
adv [DIR_NAME]

.SH DESCRIPTION
.LP
(1) [DIR_NAME] Create a directory with the provided name and cd into it.
.LP
(2) Create and cd into the next exercise either from a .../ex* dir or a project dir. Currently works only on zsh terminals, bash update is coming

.SH AUTHOR
Written by Maksim Trukhinov <eldritch.gato@gmail.com>. GitHub: <StriderDunedain>
.LP
Project HOD (Hand of God)
