.TH cln 1
.SH NAME
[DEPRECATED!] cln - prepare the directory for hand-over

.SH SYNOPSYS
cln

.SH DESCRIPTION
Delete all .out files, check norminette and list all files and dirs in this directory.

.SH SEE ALSO
This is a deprecated function, use wrt(1) instead for cleaning up and committing at the same time

.SH AUTHOR
Written by Maksim Trukhinov <eldritch.gato@gmail.com>. GitHub: <StriderDunedain>
.LP
Project HOD (Hand of God)
