.TH co 1
.SH NAME
co - open current directory or file(s) in VS Code
.SH SYNOPSYS
co [-nw] [OPTIONAL FILE_NAME]

.SH OPTIONS
.TP
.B -nw, --new-window
Open file(s) / directory in a new VS Code window

.SH DESCRIPTION
Open the current directory or, if specified, file(s) in VS Code

.SH AUTHOR
Written by Maksim Trukhinov <eldritch.gato@gmail.com>. GitHub: <StriderDunedain>
.LP
Project HOD (Hand of God)
