.TH cpl 1
.SH NAME
cpl - compile and run C/C++ programs quickly

.SH SYNOPSIS
cpl [OPTIONS]... [SOURCES]...

.SH DESCRIPTION
cpl is a small helper that compiles C or C++ source files and optionally runs the resulting program.

.SH OPTIONS
.TP
.B -s, --simple
Enable strict warnings (-Wall -Wextra -Werror)

.TP
.B -g, --debug
Enable debug symbols

.TP
.B -v, --verbose
Verbose mode: print compile and run commands

.TP
.B -n, --dry-run
Dry run: print commands without executing

.TP
.B --
Separate compiler arguments from program arguments

.SH AUTHOR
Written by Maksim Trukhinov <eldritch.gato@gmail.com>. GitHub: <StriderDunedain>
.LP
Project HOD (Hand of God)
