.TH cpl 1
.SH NAME
cpl - compile and run C/C++ programs quickly

.SH SYNOPSIS
cpl [OPTIONS]... [COMPILER_ARGUMENTS]... [-- PROGRAM_ARGUMENTS]...

.SH DESCRIPTION
cpl is a small helper that compiles C or C++ source files and optionally runs the resulting program.

.SH OPTIONS
.TP
.B -s, --simple
Enable strict warnings (-Wall -Wextra -Werror)

.TP
.B -g, --debug
Enable debug symbols

.TP
.B -v, --verbose
Verbose mode: print compile and run commands

.TP
.B -n, --dry-run
Dry run: print commands without executing

.TP
.B -o FILE, --output FILE
Write the executable to FILE instead of a.out

.TP
.B --
End compiler arguments and pass all remaining arguments to the compiled program

.SH ARGUMENTS
Before
.BR -- ,
unrecognized short options and other arguments are passed to the compiler.
At least one filename ending in a recognized C or C++ extension is required.
Unknown long options are rejected to catch misspelled cpl options.

.SH AUTHOR
Written by Maksim Trukhinov <eldritch.gato@gmail.com>. GitHub: <StriderDunedain>
.LP
Project HOD (Hand of God)
