.TH cpl 1
.SH NAME
cpl - compile a .c file and run the resulting a.out

.SH SYNOPSYS
cpl [FILE_NAME]

.SH DESCRIPTION
Compile the provided .c file and run the resulting a.out file.

.SH AUTHOR
Written by Maksim Trukhinov <eldritch.gato@gmail.com>. GitHub: <StriderDunedain>
.LP
Project HOD (Hand of God)
