.TH evl 1
.SH NAME
evl - cd into the evaluations folder and the cloned git repo

.SH SYNOPSYS
evl [GITHUB_LINK]

.SH DESCRIPTION
cd into the evaluations folder (set by EVAL_PATH), delete everything that was there, clone the provided repo and cd into it

.SH AUTHOR
Written by Maksim Trukhinov <eldritch.gato@gmail.com>. GitHub: <StriderDunedain>
.LP
Project HOD (Hand of God)
