.TH hod 1
.SH NAME
hod - display all HOD utils with their short description

.SH SYNOPSYS
hod [UTIL_NAME]

.SH DESCRIPTION
.LP
(1) List all HOD commands with their short descriptions.
.LP
(2) [UTIL_NAME] Open or create a HOD man page

.SH AUTHOR
Written by Maksim Trukhinov <eldritch.gato@gmail.com>. GitHub: <StriderDunedain>
.LP
Project HOD (Hand of God)
