.TH hod 1
.SH NAME
[DEPRECATED!] hod - display all HOD utils with their short description or edit a function's man page

.SH SYNOPSYS
hod [OPTIONAL UTIL_NAME]

.SH DESCRIPTION
.LP
(1) List all HOD commands with their short descriptions.
.LP
(2) [UTIL_NAME] Open for edit or create a HOD man page

.SH SEE ALSO
This function has been deprecated because of potenatial growth of the project and its unwieldiness. Use the man pages instead. If HOD becomes even larger, a wiki may be implemented. Users are also highly discouraged from writing to the man pages with `hod` since it opens nano on the machine's .local folder and not in the hand_of_god/man_pages which will inevitably lead to inconsistencies

.SH AUTHOR
Written by Maksim Trukhinov <eldritch.gato@gmail.com>. GitHub: <StriderDunedain>
.LP
Project HOD (Hand of God)
