.TH manup 1
.SH NAME
manup - update the man pages
.SH SYNOPSYS
manup

.SH DESCRIPTION
Copy the man pages from Hand of God's man_pages/ directory to the configured man page directory, updating any existing entries.

.SH AUTHOR
Written by Maksim Trukhinov <eldritch.gato@gmail.com>. GitHub: <StriderDunedain>
.LP
Project HOD (Hand of God)
