.TH pr 1
.SH NAME
pr - go to a project from anywhere in the system or WORK_DIR if no argument is provided

.SH SYNOPSYS
pr [PROJECT_NAME]

.SH DESCRIPTION
cd into one of the folder in the directory set by WORK_DIR (or to the working folder if no argument is provided, see work(1))

.SH SEE AlSO
work(1) for the default path pr will take if no argument is provided

.SH AUTHOR
Written by Maksim Trukhinov <eldritch.gato@gmail.com>. GitHub: <StriderDunedain>
.LP
Project HOD (Hand of God)
