.TH work 1
.SH NAME
work - go to the working folder

.SH SYNOPSYS
work

.SH DESCRIPTION
Go to the folder set by WORK_DIR_PATH

.SH SEE ALSO
cpr(1) goes to the current working folder

.SH AUTHOR
Written by Maksim Trukhinov <eldritch.gato@gmail.com>. GitHub: <StriderDunedain>
.LP
Project HOD (Hand of God)
