.TH wrt 1
.SH NAME
wrt - execute my usual git workflow for a project in 42

.SH SYNOPSIS
wrt [OPTIONS]... [MESSAGE]

.SH OPTIONS
.TP
.B --no-norm
Disable the standard 42 checks: norminette and the presence of a README.md

.TP
.B --no-readme
Disable the check for the presence of a README.md

.SH DESCRIPTION
1. Check for 42 submitting requirements (presence of a README.md and norminette compliance) unless flags are set
2. Offer to delete top-level .out, .o, and .a build artifacts
3. Stage for commit all files in the directory, commit them with the message provided (or a standard one, describing what happened to which files using git's (A), (M), etc.)
4. Push to remote

.SH AUTHOR
Written by Maksim Trukhinov <eldritch.gato@gmail.com>. GitHub: <StriderDunedain>
.LP
Project HOD (Hand of God)
