.TH wrt 1
.SH NAME
wrt - execute my usual git workflow for a project

.SH SYNOPSYS
wrt [MESSAGE]

.SH DESCRIPTION
Stage for commit all files in the directory, commit them with the message provided and pushe to remote.

.SH AUTHOR
Written by Maksim Trukhinov <eldritch.gato@gmail.com>. GitHub: <StriderDunedain>
.LP
Project HOD (Hand of God)
